### ISSUE TITLE
Allow setSpeed with animation to be zero

### ISSUE THREAD

**Issue by Lauszus** [ntoskrnl/SpeedometerView#1]
Is there any reason why you don't allow this value: https://github.com/ntoskrnl/SpeedometerView/blob/master/CardioMoodSpeedometerView/SpeedometerView/src/main/java/com/cardiomood/android/speedometer/SpeedometerView.java#L111-L112 to be 0?

I have worked around this temporarily by simply adding a very small number to the progress before calling setSpeed.

**Comment by ntoskrnl** [comment]
Lol)) you are so right! I must fix this! Actually i also found a couple of bugs... i will commit fixes soon.

**Comment by Lauszus** [comment]
Thanks. Looking forward to the update ;)
Btw have you considered pushing it to Maven central? Right now I have set up my own local Maven repository inside the libs folder: https://github.com/Lauszus/BalancingRobotFullSizeAndroid/tree/master/app/libs/com for it to work.

**Comment by Lauszus** [comment]
Any update on this? Btw here is what I have been using your library for: http://blog.tkjelectronics.dk/2014/07/full-size-diy-balancing-robot/ ;)

**Comment by ntoskrnl** [comment]
I have a lib with a few controls, not just a SpeedometerView... I think I will mark this as Deprecated, and create another repo....

**Comment by Lauszus** [comment]
Okay. I will switch to that once I update my app :)

**Comment by ntoskrnl** [comment]
Hello!
https://github.com/ntoskrnl/AndroidWidgets this is the new repo. Also I pushed the project to the maven central. They promised it will become available soon.

``` gradle
compile 'com.cardiomood.android:android-widgets:0.1'
```

**Comment by Lauszus** [comment]
@ntoskrnl awesome, thank you!
